#!/bin/bash

export PATH=/var/vcap/packages/ruby/bin:$PATH

RUN_DIR=/var/vcap/sys/run/elasticsearch_gateway
LOG_DIR=/var/vcap/sys/log/elasticsearch_gateway
PIDFILE=$RUN_DIR/elasticsearch_gateway.pid

JOB_DIR=/var/vcap/jobs/elasticsearch_gateway

source /var/vcap/packages/common/utils.sh

case $1 in

  start)
    pid_guard $PIDFILE "Elasticsearch gateway"

    mkdir -p $RUN_DIR
    mkdir -p $LOG_DIR

    echo $$ > $PIDFILE

    <% if properties.syslog_aggregator %>
    /var/vcap/packages/syslog_aggregator/setup_syslog_forwarder.sh $JOB_DIR/config
    <% end %>

    exec /var/vcap/packages/elasticsearch_gateway/services/elasticsearch/bin/elasticsearch_gateway \
         -c $JOB_DIR/config/elasticsearch_gateway.yml \
         >>$LOG_DIR/elasticsearch_gateway.stdout.log \
         2>>$LOG_DIR/elasticsearch_gateway.stderr.log

    ;;

  stop)
    kill_and_wait $PIDFILE

    ;;

  *)
    echo "Usage: elasticsearch_gateway_ctl {start|stop}"

    ;;

esac