#!/bin/sh

templates=$(dirname $0)/templates

infrastructure=$1

shift

if  [ "$infrastructure" != "warden" ] && \
    [ "$infrastructure" != "openstack" ] ; then
  echo "usage: ./generate_deployment_manifest <warden|openstack> [stubs...]"
  exit 1
fi

spiff merge \
  $templates/deployment.yml \
  $templates/jobs.yml \
  $templates/properties.yml \
  $templates/infrastructure-${infrastructure}.yml \
  $*
