---
# cloud_controller_uri: api.vcap.me
service:
  name: postgresql
  version: "9.2"
  description: 'PostgreSQL database'
  plans: ['free']
  default_plan: free
  tags: ['relational']
ip_route: localhost
#proxy:
#   host: proxy
#   port: 8080
#   keepalive: true
index: 0
token: "0xdeadbeef"
logging:
  level: debug
mbus: nats://localhost:4222
pid: /var/vcap/sys/run/postgresql_service.pid
node_timeout: 2
api_extensions:
  - snapshots
  - serialization
  - jobs
resque:
  host: localhost
  port: 5454
download_url_template: http://dl.vcap.me/serialized/%{service}/%{name}/snapshots/%{snapshot_id}?token=%{token}

plan_management:
  plans:
    free:
      low_water: 10
      high_water: 180
      lifecycle:
        snapshots:
          quota: 5
        serialization: enable
        job: enable
      #allow_over_provisioning: false

# z_interval: 30
# check_orphan_interval: 3600
# double_check_orphan_interval: 300
