---
service_name: postgresql
snapshots_base_dir: /var/vcap/services/
serialization_base_dir: /var/vcap/services/
local_db: sqlite3:/var/vcap/services/postgresql/postgresql_node.db
snapshot_quota: 5
# optional download tuning
serialization:
  max_download_size_mb: 10
  max_download_redirects: 5
# Temp directory to save uploaded file
tmp_dir: /tmp
resque:
  host: localhost
  port: 5454
index: 0
node_id: postgresql_node_free_1
download_url_template: http://dl.vcap.me/serialized/%{service}/%{name}/snapshots/%{snapshot_id}?token=%{token}
logging:
  level: debug
# addtional options
postgresql:
  '9.0':
    host: 127.0.0.1
    port: 5432
    user: vcap
    pass: vcap
    database: postgres
    restore_bin: pg_restore
    dump_bin: pg_dump
  '9.1':
    host: 127.0.0.1
    port: 5433
    user: vcap
    pass: vcap
    database: postgres
    restore_bin: pg_restore
    dump_bin: pg_dump
  '9.2':
    host: 127.0.0.1
    port: 5434
    user: vcap
    pass: vcap
    database: postgres
    restore_bin: pg_restore
    dump_bin: pg_dump
use_warden: false
